title: kkryama.github.io
description: _yama_P_'s page
theme: jekyll-theme-primer

collections:
  diary:
    output: true
    permalink: /diary/:name/
  creation:
    output: true
    permalink: /creation/:name/

